package codegen

// This file contains the template source for the conversion helpers that are
// emitted alongside every generated package.  The helpers translate between
// typed structs (Create/Update) and the map[string]any expected by port.Repository
// and port.Service.
//
// Rather than generating them via reflection (which would require the generated
// package to import "reflect"), we use encoding/json round-trip conversion.
// This is allocation-heavy but correct and maintenance-free as fields evolve.

// convertHelpersSource is injected into every generated package as convert.go.
// It must be a valid Go source file in the package being generated (the
// package declaration is filled in at generation time).
const convertHelpersSource = `// Code generated by stellar-drive; DO NOT EDIT.
package PACKAGE_NAME

import (
	"encoding/json"
	"fmt"
)

// createToMap converts a typed Create struct into a map[string]any by
// marshalling to JSON and back.  This preserves omitempty semantics defined
// on the struct tags and avoids reflection.
func createToMap(v any) map[string]any {
	return structToMap(v)
}

// updateToMap converts a typed Update struct into a map[string]any, filtering
// out nil pointer fields so only changed keys reach the repository.
func updateToMap(v any) map[string]any {
	return structToMap(v)
}

// structToMap marshals v to JSON and decodes the result into map[string]any.
// Fields with json:"...,omitempty" that are nil/zero are absent from the map.
func structToMap(v any) map[string]any {
	b, err := json.Marshal(v)
	if err != nil {
		panic(fmt.Sprintf("structToMap: marshal: %v", err))
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		panic(fmt.Sprintf("structToMap: unmarshal: %v", err))
	}
	return m
}
`
