package codegen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/digitally-rendered/stellar-drive/internal/stringutil"
	"github.com/digitally-rendered/stellar-drive/pkg/core/schema"
)

var graphqlTemplate = template.Must(template.New("graphql").Funcs(template.FuncMap{
	"pascal":      stringutil.ToPascalCase,
	"gqlType":     gqlType,
	"gqlNonNull":  gqlNonNull,
	"gqlInputType": gqlInputType,
	"lower":       strings.ToLower,
	"camel":       stringutil.ToCamelCase,
	"plural":      stringutil.Pluralize,
}).Parse(`# Code generated by stellar-drive; DO NOT EDIT.
# Schema: {{ .SchemaName }} v{{ .Version }}

# ---------------------------------------------------------------------------
# {{ pascal .SchemaName }} – document type
# ---------------------------------------------------------------------------

type {{ pascal .SchemaName }} {
  id: ID!
  entityId: String!
  recordVersion: Int!
  schemaVersion: String!
  schemaName: String!
  etag: String!
  createdAt: String!
  updatedAt: String!
  deletedAt: String
  createdBy: String
  updatedBy: String
  deletedBy: String
{{ range .Fields }}  {{ camel .Name }}: {{ gqlNonNull .Required (gqlType .) }}
{{ end }}}

# ---------------------------------------------------------------------------
# {{ pascal .SchemaName }}Create – input for mutations
# ---------------------------------------------------------------------------

input {{ pascal .SchemaName }}Create {
{{ range .Fields }}  {{ camel .Name }}: {{ gqlNonNull .Required (gqlInputType .) }}
{{ end }}}

# ---------------------------------------------------------------------------
# {{ pascal .SchemaName }}Update – partial input for patch mutations
# ---------------------------------------------------------------------------

input {{ pascal .SchemaName }}Update {
{{ range .Fields }}  {{ camel .Name }}: {{ gqlInputType . }}
{{ end }}}

# ---------------------------------------------------------------------------
# Queries and Mutations
# ---------------------------------------------------------------------------

type {{ pascal .SchemaName }}ListResult {
  items: [{{ pascal .SchemaName }}!]!
  total: Int!
  hasMore: Boolean!
  cursor: String
}

type Query {
  {{ camel .SchemaName }}(entityId: ID!): {{ pascal .SchemaName }}
  {{ camel (plural .SchemaName) }}(limit: Int, offset: Int, cursor: String): {{ pascal .SchemaName }}ListResult!
}

type Mutation {
  create{{ pascal .SchemaName }}(input: {{ pascal .SchemaName }}Create!): {{ pascal .SchemaName }}!
  update{{ pascal .SchemaName }}(entityId: ID!, input: {{ pascal .SchemaName }}Update!): {{ pascal .SchemaName }}!
  delete{{ pascal .SchemaName }}(entityId: ID!): Boolean!
}
`))

// graphqlTemplateData is the data passed to graphqlTemplate.
type graphqlTemplateData struct {
	SchemaName string
	Version    string
	Fields     []schema.FieldDefinition
}

// GenerateGraphQL returns GraphQL SDL text for the given schema.
func GenerateGraphQL(def *schema.SchemaDefinition) (string, error) {
	data := graphqlTemplateData{
		SchemaName: def.Name,
		Version:    def.Version,
		Fields:     schema.CreateFields(def),
	}

	var buf bytes.Buffer
	if err := graphqlTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute graphql template: %w", err)
	}
	return buf.String(), nil
}

// ---------------------------------------------------------------------------
// GraphQL type mapping helpers
// ---------------------------------------------------------------------------

// gqlType maps a FieldDefinition to its GraphQL type (without non-null modifier).
func gqlType(f schema.FieldDefinition) string {
	if len(f.Enum) > 0 {
		return "String" // enum values are strings in GraphQL unless a custom scalar is used
	}
	switch f.JSONType {
	case "string":
		if f.Format == "date-time" {
			return "String" // represent as ISO-8601 string; clients parse
		}
		return "String"
	case "number":
		return "Float"
	case "integer":
		return "Int"
	case "boolean":
		return "Boolean"
	case "array":
		itemType := "String"
		if f.Items != nil {
			itemType = gqlType(*f.Items)
		}
		return "[" + itemType + "]"
	case "object":
		return "String" // JSON-encoded string for nested objects
	default:
		return "String"
	}
}

// gqlInputType returns the GraphQL input type for a field.
// For most fields this is the same as gqlType.
func gqlInputType(f schema.FieldDefinition) string {
	return gqlType(f)
}

// gqlNonNull wraps a type with the GraphQL non-null modifier (!) when required.
func gqlNonNull(required bool, typeName string) string {
	if required {
		return typeName + "!"
	}
	return typeName
}
