package codegen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/digitally-rendered/stellar-drive/internal/stringutil"
	"github.com/digitally-rendered/stellar-drive/pkg/core/schema"
)

var handlerTemplate = template.Must(template.New("handler").Funcs(template.FuncMap{
	"pascal": stringutil.ToPascalCase,
	"plural": stringutil.Pluralize,
	"kebab":  toKebabPath,
	"lower":  strings.ToLower,
}).Parse(`// Code generated by stellar-drive; DO NOT EDIT.
package {{ .PackageName }}

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// {{ .TypePrefix }}Handler provides typed HTTP handlers for the {{ .SchemaName }}
// resource. It wraps a {{ .TypePrefix }}Service and renders JSON responses.
type {{ .TypePrefix }}Handler struct {
	svc *{{ .TypePrefix }}Service
}

// New{{ .TypePrefix }}Handler constructs a handler backed by svc.
func New{{ .TypePrefix }}Handler(svc *{{ .TypePrefix }}Service) *{{ .TypePrefix }}Handler {
	return &{{ .TypePrefix }}Handler{svc: svc}
}

// Routes returns a chi.Router with all five CRUD routes.
func (h *{{ .TypePrefix }}Handler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Post("/", h.Create)
	r.Get("/", h.List)
	r.Get("/{entityID}", h.GetByID)
	r.Patch("/{entityID}", h.Update)
	r.Delete("/{entityID}", h.Delete)
	return r
}

// Create handles POST /
func (h *{{ .TypePrefix }}Handler) Create(w http.ResponseWriter, r *http.Request) {
	var input {{ .TypePrefix }}Create
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		writeHandlerError(w, http.StatusBadRequest, err.Error())
		return
	}
	doc, err := h.svc.Create(r.Context(), &input)
	if err != nil {
		writeHandlerError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeHandlerJSON(w, http.StatusCreated, doc)
}

// List handles GET /
func (h *{{ .TypePrefix }}Handler) List(w http.ResponseWriter, r *http.Request) {
	result, err := h.svc.List(r.Context(), nil)
	if err != nil {
		writeHandlerError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeHandlerJSON(w, http.StatusOK, result)
}

// GetByID handles GET /{entityID}
func (h *{{ .TypePrefix }}Handler) GetByID(w http.ResponseWriter, r *http.Request) {
	entityID := chi.URLParam(r, "entityID")
	if entityID == "" {
		writeHandlerError(w, http.StatusBadRequest, "entityID is required")
		return
	}
	doc, err := h.svc.FindByID(r.Context(), entityID)
	if err != nil {
		writeHandlerError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeHandlerJSON(w, http.StatusOK, doc)
}

// Update handles PATCH /{entityID}
func (h *{{ .TypePrefix }}Handler) Update(w http.ResponseWriter, r *http.Request) {
	entityID := chi.URLParam(r, "entityID")
	if entityID == "" {
		writeHandlerError(w, http.StatusBadRequest, "entityID is required")
		return
	}
	var input {{ .TypePrefix }}Update
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		writeHandlerError(w, http.StatusBadRequest, err.Error())
		return
	}
	doc, err := h.svc.Update(r.Context(), entityID, &input)
	if err != nil {
		writeHandlerError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeHandlerJSON(w, http.StatusOK, doc)
}

// Delete handles DELETE /{entityID}
func (h *{{ .TypePrefix }}Handler) Delete(w http.ResponseWriter, r *http.Request) {
	entityID := chi.URLParam(r, "entityID")
	if entityID == "" {
		writeHandlerError(w, http.StatusBadRequest, "entityID is required")
		return
	}
	if err := h.svc.Delete(r.Context(), entityID); err != nil {
		writeHandlerError(w, http.StatusInternalServerError, err.Error())
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

func writeHandlerJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func writeHandlerError(w http.ResponseWriter, status int, msg string) {
	writeHandlerJSON(w, status, map[string]string{"error": msg})
}
`))

// handlerTemplateData is the data passed to handlerTemplate.
type handlerTemplateData struct {
	PackageName string
	ModulePath  string
	SchemaName  string
	TypePrefix  string
}

// GenerateHandler returns Go source for a typed HTTP handler.
func GenerateHandler(def *schema.SchemaDefinition, pkgName, modulePath string) (string, error) {
	data := handlerTemplateData{
		PackageName: pkgName,
		ModulePath:  modulePath,
		SchemaName:  def.Name,
		TypePrefix:  stringutil.ToPascalCase(def.Name),
	}

	var buf bytes.Buffer
	if err := handlerTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute handler template: %w", err)
	}
	return buf.String(), nil
}

// toKebabPath converts a schema name to a URL-friendly kebab-case path segment.
func toKebabPath(s string) string {
	return strings.ToLower(strings.ReplaceAll(s, "_", "-"))
}
