package codegen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/digitally-rendered/stellar-drive/internal/stringutil"
	"github.com/digitally-rendered/stellar-drive/pkg/core/schema"
)

// modelsTemplate is the text/template used to render all three model variants
// for a given schema.
var modelsTemplate = template.Must(template.New("models").Funcs(template.FuncMap{
	"pascal":       stringutil.ToPascalCase,
	"fieldGoType":  fieldGoType,
	"jsonTag":      jsonTag,
	"hasTimeField": hasTimeField,
	"hasEnumField": hasEnumFields,
	"enumTypeName": enumTypeName,
	"enumConsts":   enumConsts,
}).Parse(`// Code generated by stellar-drive; DO NOT EDIT.
package {{ .PackageName }}
{{ if .NeedsTime }}
import "time"
{{ end }}
// ---------------------------------------------------------------------------
// Enum types
// ---------------------------------------------------------------------------
{{ range .Fields }}{{ if .Enum }}
// {{ enumTypeName $.TypePrefix .Name }} is the set of accepted values for the {{ .Name }} field.
type {{ enumTypeName $.TypePrefix .Name }} string

const (
{{ range enumConsts $.TypePrefix .Name .Enum }}	{{ .ConstName }} {{ .TypeName }} = "{{ .Value }}"
{{ end }})
{{ end }}{{ end }}

// ---------------------------------------------------------------------------
// Document variant – full persisted document including audit fields
// ---------------------------------------------------------------------------

// {{ .TypePrefix }}Document is the fully persisted representation of a
// {{ .SchemaName }} record, including all generated audit fields.
type {{ .TypePrefix }}Document struct {
	ID            string     ` + "`" + `json:"id"` + "`" + `
	EntityID      string     ` + "`" + `json:"entity_id"` + "`" + `
	RecordVersion int64      ` + "`" + `json:"record_version"` + "`" + `
	SchemaVersion string     ` + "`" + `json:"schema_version"` + "`" + `
	SchemaName    string     ` + "`" + `json:"schema_name"` + "`" + `
	ETag          string     ` + "`" + `json:"etag"` + "`" + `
	CreatedAt     time.Time  ` + "`" + `json:"created_at"` + "`" + `
	UpdatedAt     time.Time  ` + "`" + `json:"updated_at"` + "`" + `
	DeletedAt     *time.Time ` + "`" + `json:"deleted_at,omitempty"` + "`" + `
	CreatedBy     string     ` + "`" + `json:"created_by,omitempty"` + "`" + `
	UpdatedBy     string     ` + "`" + `json:"updated_by,omitempty"` + "`" + `
	DeletedBy     string     ` + "`" + `json:"deleted_by,omitempty"` + "`" + `
{{ range .Fields }}	{{ pascal .Name }} {{ fieldGoType $.TypePrefix . false }} {{ jsonTag .Name .Required false }}
{{ end }}}

// ---------------------------------------------------------------------------
// Create variant – fields accepted on creation (no audit fields)
// ---------------------------------------------------------------------------

// {{ .TypePrefix }}Create carries the user-supplied fields for creating a new
// {{ .SchemaName }} record. Required fields must be present; optional fields
// are tagged omitempty.
type {{ .TypePrefix }}Create struct {
{{ range .Fields }}	{{ pascal .Name }} {{ fieldGoType $.TypePrefix . false }} {{ jsonTag .Name .Required false }}
{{ end }}}

// ---------------------------------------------------------------------------
// Update variant – all fields optional (PATCH semantics)
// ---------------------------------------------------------------------------

// {{ .TypePrefix }}Update carries the fields the caller wants to change in an
// existing {{ .SchemaName }} record. Every field is a pointer so the caller
// can supply only the subset to update.
type {{ .TypePrefix }}Update struct {
{{ range .Fields }}	{{ pascal .Name }} {{ fieldGoType $.TypePrefix . true }} {{ jsonTag .Name false true }}
{{ end }}}
`))

// modelsTemplateData is the data passed to modelsTemplate.
type modelsTemplateData struct {
	PackageName string
	SchemaName  string
	TypePrefix  string
	Fields      []schema.FieldDefinition
	NeedsTime   bool
}

// GenerateModels returns Go source for the three model variants of def.
func GenerateModels(def *schema.SchemaDefinition, pkgName, _ string) (string, error) {
	typePrefix := stringutil.ToPascalCase(def.Name)
	fields := schema.CreateFields(def) // user fields only; Document embeds fixed audit fields

	needsTime := false
	for _, f := range fields {
		if f.Format == "date-time" || f.GoType == "time.Time" || f.GoType == "*time.Time" {
			needsTime = true
			break
		}
	}

	data := modelsTemplateData{
		PackageName: pkgName,
		SchemaName:  def.Name,
		TypePrefix:  typePrefix,
		Fields:      fields,
		NeedsTime:   needsTime,
	}

	// Document always has time fields (audit).
	data.NeedsTime = true

	var buf bytes.Buffer
	if err := modelsTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute models template: %w", err)
	}
	return buf.String(), nil
}

// ---------------------------------------------------------------------------
// Template helper functions
// ---------------------------------------------------------------------------

// fieldGoType returns the Go type for a field. When forUpdate is true, the
// type is wrapped in a pointer (except for types that are already pointers or
// interfaces).
func fieldGoType(typePrefix string, f schema.FieldDefinition, forUpdate bool) string {
	base := resolvedGoType(typePrefix, f)
	if !forUpdate {
		return base
	}
	// Already a pointer or interface – leave as-is.
	if strings.HasPrefix(base, "*") || base == "any" || strings.HasPrefix(base, "[]") || strings.HasPrefix(base, "map[") {
		return base
	}
	return "*" + base
}

// resolvedGoType returns the Go type string for a field, using the pre-resolved
// GoType from the FieldDefinition when available and synthesising enum types.
func resolvedGoType(typePrefix string, f schema.FieldDefinition) string {
	if len(f.Enum) > 0 {
		return enumTypeName(typePrefix, f.Name)
	}
	if f.GoType != "" {
		return f.GoType
	}
	// Fallback mapping identical to schema.resolveGoType.
	switch f.JSONType {
	case "string":
		if f.Format == "date-time" {
			return "time.Time"
		}
		return "string"
	case "number":
		return "float64"
	case "integer":
		return "int64"
	case "boolean":
		return "bool"
	case "array":
		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

// jsonTag builds a struct tag for a JSON field name.
// When required is false the omitempty option is added.
// When forUpdate is true omitempty is always added.
func jsonTag(name string, required, forUpdate bool) string {
	if required && !forUpdate {
		return fmt.Sprintf("`json:%q`", name)
	}
	return fmt.Sprintf("`json:\"%s,omitempty\"`", name)
}

// hasTimeField reports whether any field in the slice uses time.Time.
func hasTimeField(fields []schema.FieldDefinition) bool {
	for _, f := range fields {
		if f.Format == "date-time" || f.GoType == "time.Time" || f.GoType == "*time.Time" {
			return true
		}
	}
	return false
}

// hasEnumFields reports whether any field carries an Enum constraint.
func hasEnumFields(fields []schema.FieldDefinition) bool {
	for _, f := range fields {
		if len(f.Enum) > 0 {
			return true
		}
	}
	return false
}

// enumTypeName returns the Go type name for an enum field,
// e.g. typePrefix="Order", fieldName="status" → "OrderStatus".
func enumTypeName(typePrefix, fieldName string) string {
	return typePrefix + stringutil.ToPascalCase(fieldName)
}

// enumConst is a single constant declaration for an enum value.
type enumConst struct {
	ConstName string
	TypeName  string
	Value     string
}

// enumConsts generates constant declarations for all enum values of a field.
func enumConsts(typePrefix, fieldName string, values []any) []enumConst {
	typeName := enumTypeName(typePrefix, fieldName)
	out := make([]enumConst, 0, len(values))
	for _, v := range values {
		s := fmt.Sprintf("%v", v)
		constName := typeName + stringutil.ToPascalCase(strings.ReplaceAll(s, "-", "_"))
		out = append(out, enumConst{
			ConstName: constName,
			TypeName:  typeName,
			Value:     s,
		})
	}
	return out
}
