package codegen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/digitally-rendered/stellar-drive/internal/stringutil"
	"github.com/digitally-rendered/stellar-drive/pkg/core/schema"
)

// overridesTemplate renders a per-schema stub file that wires up empty guards,
// validators, transforms, and optional handler overrides for every CRUD
// operation. Users fill in the function bodies; stellar-drive calls them on
// every matching request.
//
// The generated file is intended to be edited by hand and is NEVER overwritten
// by subsequent runs of `stellar generate --overrides`. This keeps iterative
// regeneration safe even after consumers add real logic.
var overridesTemplate = template.Must(template.New("overrides").Parse(`// Overrides stub for the {{ .SchemaName }} schema.
//
// Generated by stellar-drive. This file is intentionally NOT marked
// "DO NOT EDIT" — fill in the function bodies below and register any you
// want active inside Register{{ .TypePrefix }}Overrides.
//
// Re-running ` + "`stellar generate --overrides`" + ` will skip this file when it
// already exists, so your edits are preserved.
package {{ .PackageName }}

import (
	"context"
	"net/http"

	"{{ .ModulePath }}/pkg/core/registry"
)

// Register{{ .TypePrefix }}Overrides wires the hooks below into the supplied
// FunctionRegistry. Call this from your main.go after constructing the
// registry and before passing it to engine.WithFunctionRegistry.
//
//	funcReg := registry.NewFunctionRegistry()
//	{{ .PackageName }}.Register{{ .TypePrefix }}Overrides(funcReg)
//	eng := engine.New(cfg, engine.WithFunctionRegistry(funcReg))
func Register{{ .TypePrefix }}Overrides(reg *registry.FunctionRegistry) {
	// Uncomment the lines for hooks you implement below. Anything left
	// commented falls through to the stellar-drive default pipeline.

	// reg.RegisterGuard("{{ .SchemaName }}", registry.OpCreate, registry.Scope{}, guardCreate{{ .TypePrefix }})
	// reg.RegisterGuard("{{ .SchemaName }}", registry.OpUpdate, registry.Scope{}, guardUpdate{{ .TypePrefix }})
	// reg.RegisterGuard("{{ .SchemaName }}", registry.OpDelete, registry.Scope{}, guardDelete{{ .TypePrefix }})

	// reg.RegisterValidator("{{ .SchemaName }}", registry.OpCreate, registry.Scope{}, validateCreate{{ .TypePrefix }})
	// reg.RegisterValidator("{{ .SchemaName }}", registry.OpUpdate, registry.Scope{}, validateUpdate{{ .TypePrefix }})

	// reg.RegisterTransform("{{ .SchemaName }}", registry.OpCreate, registry.Scope{}, transformCreate{{ .TypePrefix }})
	// reg.RegisterTransform("{{ .SchemaName }}", registry.OpUpdate, registry.Scope{}, transformUpdate{{ .TypePrefix }})

	// reg.RegisterHandler("{{ .SchemaName }}", registry.OpList, registry.Scope{}, handleList{{ .TypePrefix }})

	_ = reg // silence unused-parameter lint when no hooks are registered
}

// ---------------------------------------------------------------------------
// Guard hooks — deny requests before the service pipeline runs.
// Return nil to allow, any error to reject.
// ---------------------------------------------------------------------------

func guardCreate{{ .TypePrefix }}(ctx context.Context, r *http.Request) error {
	// TODO: implement or delete.
	return nil
}

func guardUpdate{{ .TypePrefix }}(ctx context.Context, r *http.Request) error {
	// TODO: implement or delete.
	return nil
}

func guardDelete{{ .TypePrefix }}(ctx context.Context, r *http.Request) error {
	// TODO: implement or delete.
	return nil
}

// ---------------------------------------------------------------------------
// Validator hooks — run after JSON Schema validation, before persistence.
// Return nil if data is acceptable, any error to reject.
// ---------------------------------------------------------------------------

func validateCreate{{ .TypePrefix }}(ctx context.Context, schemaName string, data map[string]any) error {
	// TODO: implement or delete.
	return nil
}

func validateUpdate{{ .TypePrefix }}(ctx context.Context, schemaName string, data map[string]any) error {
	// TODO: implement or delete.
	return nil
}

// ---------------------------------------------------------------------------
// Transform hooks — mutate or enrich data before it reaches the repository.
// Return the (possibly modified) map to continue; return an error to abort.
// ---------------------------------------------------------------------------

func transformCreate{{ .TypePrefix }}(ctx context.Context, schemaName string, data map[string]any) (map[string]any, error) {
	// TODO: implement or delete.
	return data, nil
}

func transformUpdate{{ .TypePrefix }}(ctx context.Context, schemaName string, data map[string]any) (map[string]any, error) {
	// TODO: implement or delete.
	return data, nil
}

// ---------------------------------------------------------------------------
// Handler overrides — replace the default stellar-drive handler entirely.
// When registered, the handler is called directly; guards, validators, and
// transforms for the same operation are bypassed.
// ---------------------------------------------------------------------------

func handleList{{ .TypePrefix }}(w http.ResponseWriter, r *http.Request) {
	// TODO: implement or delete.
	w.WriteHeader(http.StatusNotImplemented)
}
`))

// overridesTemplateData is the data passed to overridesTemplate.
type overridesTemplateData struct {
	PackageName string
	ModulePath  string
	SchemaName  string
	TypePrefix  string
}

// GenerateOverrides returns Go source for a per-schema overrides stub file.
// The output is intended for direct editing by consumers; it is not regenerated
// in place once it exists on disk.
func GenerateOverrides(def *schema.SchemaDefinition, pkgName, modulePath string) (string, error) {
	data := overridesTemplateData{
		PackageName: pkgName,
		ModulePath:  modulePath,
		SchemaName:  def.Name,
		TypePrefix:  stringutil.ToPascalCase(def.Name),
	}

	var buf bytes.Buffer
	if err := overridesTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute overrides template: %w", err)
	}
	return buf.String(), nil
}

// WriteOverridesIfAbsent writes the overrides stub for every registered schema
// under outputDir/<schemaName>/<schemaName>_overrides.go. Existing files are
// preserved — this function is safe to re-run as schemas evolve.
func (g *Generator) WriteOverridesIfAbsent() error {
	for _, name := range g.registry.Names() {
		def, err := g.registry.Get(name, "")
		if err != nil {
			return fmt.Errorf("get schema %q: %w", name, err)
		}

		dir := filepath.Join(g.outputDir, name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create output dir %q: %w", dir, err)
		}

		path := filepath.Join(dir, name+"_overrides.go")
		if _, err := os.Stat(path); err == nil {
			// Preserve hand-edited overrides file.
			continue
		}

		pkgName := sanitizePackageName(name)
		src, err := GenerateOverrides(def, pkgName, g.modulePath)
		if err != nil {
			return fmt.Errorf("generate overrides for %q: %w", name, err)
		}
		if err := writeGoFile(path, src); err != nil {
			return fmt.Errorf("write overrides for %q: %w", name, err)
		}
	}
	return nil
}
