package codegen

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/digitally-rendered/stellar-drive/internal/stringutil"
	"github.com/digitally-rendered/stellar-drive/pkg/core/schema"
)

var repositoryTemplate = template.Must(template.New("repository").Parse(`// Code generated by stellar-drive; DO NOT EDIT.
package {{ .PackageName }}

import (
	"context"

	"{{ .ModulePath }}/pkg/core/model"
	"{{ .ModulePath }}/pkg/core/port"
	"{{ .ModulePath }}/pkg/core/query"
)

// {{ .TypePrefix }}Repository wraps port.Repository with typed methods for the
// {{ .SchemaName }} schema.
type {{ .TypePrefix }}Repository struct {
	inner      port.Repository
	schemaName string
}

// New{{ .TypePrefix }}Repository constructs a typed repository backed by repo.
func New{{ .TypePrefix }}Repository(repo port.Repository) *{{ .TypePrefix }}Repository {
	return &{{ .TypePrefix }}Repository{
		inner:      repo,
		schemaName: "{{ .SchemaName }}",
	}
}

// Create persists a new {{ .SchemaName }} record from the typed input and
// returns the full stored document.
func (r *{{ .TypePrefix }}Repository) Create(ctx context.Context, input *{{ .TypePrefix }}Create) (*model.Document, error) {
	data := createToMap(input)
	doc, err := r.inner.Create(ctx, r.schemaName, data)
	if err != nil {
		return nil, err
	}
	return doc, nil
}

// FindByID retrieves the current {{ .SchemaName }} document for entityID.
func (r *{{ .TypePrefix }}Repository) FindByID(ctx context.Context, entityID string) (*model.Document, error) {
	return r.inner.FindByID(ctx, r.schemaName, entityID)
}

// List executes q and returns a paginated result set.
func (r *{{ .TypePrefix }}Repository) List(ctx context.Context, q *query.Query) (*model.ListResult, error) {
	return r.inner.List(ctx, r.schemaName, q)
}

// Update applies the typed patch to the existing {{ .SchemaName }} document
// identified by entityID.
func (r *{{ .TypePrefix }}Repository) Update(ctx context.Context, entityID string, input *{{ .TypePrefix }}Update) (*model.Document, error) {
	data := updateToMap(input)
	doc, err := r.inner.Update(ctx, r.schemaName, entityID, data)
	if err != nil {
		return nil, err
	}
	return doc, nil
}

// Delete soft-deletes the {{ .SchemaName }} document identified by entityID.
func (r *{{ .TypePrefix }}Repository) Delete(ctx context.Context, entityID string) error {
	return r.inner.Delete(ctx, r.schemaName, entityID)
}
`))

// repoTemplateData is the data passed to repositoryTemplate.
type repoTemplateData struct {
	PackageName string
	ModulePath  string
	SchemaName  string
	TypePrefix  string
}

// GenerateRepository returns Go source for a typed repository wrapper.
func GenerateRepository(def *schema.SchemaDefinition, pkgName, modulePath string) (string, error) {
	data := repoTemplateData{
		PackageName: pkgName,
		ModulePath:  modulePath,
		SchemaName:  def.Name,
		TypePrefix:  stringutil.ToPascalCase(def.Name),
	}

	var buf bytes.Buffer
	if err := repositoryTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute repository template: %w", err)
	}
	return buf.String(), nil
}
