package codegen

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/digitally-rendered/stellar-drive/internal/stringutil"
	"github.com/digitally-rendered/stellar-drive/pkg/core/schema"
)

var serviceTemplate = template.Must(template.New("service").Parse(`// Code generated by stellar-drive; DO NOT EDIT.
package {{ .PackageName }}

import (
	"context"

	"{{ .ModulePath }}/pkg/core/model"
	"{{ .ModulePath }}/pkg/core/port"
	"{{ .ModulePath }}/pkg/core/query"
)

// {{ .TypePrefix }}Service wraps port.Service with typed methods for the
// {{ .SchemaName }} schema.
type {{ .TypePrefix }}Service struct {
	inner      port.Service
	schemaName string
}

// New{{ .TypePrefix }}Service constructs a typed service backed by svc.
func New{{ .TypePrefix }}Service(svc port.Service) *{{ .TypePrefix }}Service {
	return &{{ .TypePrefix }}Service{
		inner:      svc,
		schemaName: "{{ .SchemaName }}",
	}
}

// Create validates input against the {{ .SchemaName }} schema and persists it.
func (s *{{ .TypePrefix }}Service) Create(ctx context.Context, input *{{ .TypePrefix }}Create) (*model.Document, error) {
	data := createToMap(input)
	return s.inner.Create(ctx, s.schemaName, data)
}

// FindByID retrieves the current {{ .SchemaName }} document for entityID.
func (s *{{ .TypePrefix }}Service) FindByID(ctx context.Context, entityID string) (*model.Document, error) {
	return s.inner.FindByID(ctx, s.schemaName, entityID)
}

// List executes q and returns a paginated result set.
func (s *{{ .TypePrefix }}Service) List(ctx context.Context, q *query.Query) (*model.ListResult, error) {
	return s.inner.List(ctx, s.schemaName, q)
}

// Update applies the typed patch to the existing {{ .SchemaName }} document.
func (s *{{ .TypePrefix }}Service) Update(ctx context.Context, entityID string, input *{{ .TypePrefix }}Update) (*model.Document, error) {
	data := updateToMap(input)
	return s.inner.Update(ctx, s.schemaName, entityID, data)
}

// Delete soft-deletes the {{ .SchemaName }} document identified by entityID.
func (s *{{ .TypePrefix }}Service) Delete(ctx context.Context, entityID string) error {
	return s.inner.Delete(ctx, s.schemaName, entityID)
}
`))

// svcTemplateData is the data passed to serviceTemplate.
type svcTemplateData struct {
	PackageName string
	ModulePath  string
	SchemaName  string
	TypePrefix  string
}

// GenerateService returns Go source for a typed service wrapper.
func GenerateService(def *schema.SchemaDefinition, pkgName, modulePath string) (string, error) {
	data := svcTemplateData{
		PackageName: pkgName,
		ModulePath:  modulePath,
		SchemaName:  def.Name,
		TypePrefix:  stringutil.ToPascalCase(def.Name),
	}

	var buf bytes.Buffer
	if err := serviceTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute service template: %w", err)
	}
	return buf.String(), nil
}
