package sdk

import (
	"fmt"
	"strings"

	"github.com/digitally-rendered/stellar-drive/internal/stringutil"
	"github.com/digitally-rendered/stellar-drive/pkg/core/schema"
)

// ClientGenerator generates a typed Go HTTP client SDK from registered schemas.
// The generator produces string content for three files: models.go, client.go,
// and errors.go. It does not write to disk; callers receive the file map and
// decide what to do with it.
type ClientGenerator struct {
	registry   *schema.Registry
	baseURL    string
	modulePath string
	outputDir  string
}

// ClientOption configures a ClientGenerator.
type ClientOption func(*ClientGenerator)

// WithBaseURL sets the default base URL embedded in the generated client.
func WithBaseURL(url string) ClientOption {
	return func(g *ClientGenerator) {
		g.baseURL = url
	}
}

// WithModulePath sets the Go module path used in generated package declarations
// and import paths.
func WithModulePath(path string) ClientOption {
	return func(g *ClientGenerator) {
		g.modulePath = path
	}
}

// NewClientGenerator creates a new ClientGenerator that writes generated files
// into outputDir. The registry supplies schema definitions; opts apply optional
// configuration.
func NewClientGenerator(reg *schema.Registry, outputDir string, opts ...ClientOption) *ClientGenerator {
	g := &ClientGenerator{
		registry:  reg,
		outputDir: outputDir,
	}
	for _, o := range opts {
		o(g)
	}
	return g
}

// Generate produces the SDK source files as a map[filename]content. The three
// keys are "models.go", "client.go", and "errors.go". The generated code only
// depends on the Go standard library.
func (g *ClientGenerator) Generate() (map[string]string, error) {
	defs := g.registry.List()

	modelsContent, err := g.generateModels(defs)
	if err != nil {
		return nil, fmt.Errorf("sdk: generate models: %w", err)
	}

	clientContent, err := g.generateClient(defs)
	if err != nil {
		return nil, fmt.Errorf("sdk: generate client: %w", err)
	}

	errorsContent := g.generateErrors()

	return map[string]string{
		"models.go": modelsContent,
		"client.go": clientContent,
		"errors.go": errorsContent,
	}, nil
}

// ---------------------------------------------------------------------------
// models.go generation
// ---------------------------------------------------------------------------

// generateModels returns the content of models.go containing per-schema
// structs: {Name}, {Name}Create, {Name}Update, plus the generic Document
// wrapper and list helpers.
func (g *ClientGenerator) generateModels(defs []*schema.SchemaDefinition) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by stellar-drive; DO NOT EDIT.\n")
	b.WriteString("package sdkclient\n\n")
	b.WriteString("import \"time\"\n\n")

	// Generic helpers that are schema-agnostic.
	b.WriteString(`// ResponseEnvelope wraps every API response with success/error metadata.
type ResponseEnvelope[T any] struct {
	Success bool           ` + "`json:\"success\"`" + `
	Data    T              ` + "`json:\"data,omitempty\"`" + `
	Error   *ErrorResponse ` + "`json:\"error,omitempty\"`" + `
}

// ListResult holds a page of items along with pagination state.
type ListResult[T any] struct {
	Items   []T    ` + "`json:\"items\"`" + `
	Total   int64  ` + "`json:\"total\"`" + `
	HasMore bool   ` + "`json:\"has_more\"`" + `
	Cursor  string ` + "`json:\"cursor,omitempty\"`" + `
}

// ListOptions parameterises a List request.
type ListOptions struct {
	Limit  int    ` + "`json:\"limit,omitempty\"`" + `
	Offset int    ` + "`json:\"offset,omitempty\"`" + `
	Cursor string ` + "`json:\"cursor,omitempty\"`" + `
}

// Document wraps any entity with its full set of server-generated audit fields.
type Document[T any] struct {
	ID            string     ` + "`json:\"id\"`" + `
	EntityID      string     ` + "`json:\"entity_id\"`" + `
	RecordVersion int64      ` + "`json:\"record_version\"`" + `
	SchemaVersion string     ` + "`json:\"schema_version\"`" + `
	SchemaName    string     ` + "`json:\"schema_name\"`" + `
	ETag          string     ` + "`json:\"etag\"`" + `
	CreatedAt     time.Time  ` + "`json:\"created_at\"`" + `
	UpdatedAt     time.Time  ` + "`json:\"updated_at\"`" + `
	DeletedAt     *time.Time ` + "`json:\"deleted_at,omitempty\"`" + `
	CreatedBy     string     ` + "`json:\"created_by,omitempty\"`" + `
	UpdatedBy     string     ` + "`json:\"updated_by,omitempty\"`" + `
	DeletedBy     string     ` + "`json:\"deleted_by,omitempty\"`" + `
	Data          T          ` + "`json:\"data\"`" + `
}

`)

	for _, def := range defs {
		if err := writeSchemaModels(&b, def); err != nil {
			return "", fmt.Errorf("schema %q: %w", def.Name, err)
		}
	}

	return b.String(), nil
}

// writeSchemaModels appends the three model variants for def to b.
func writeSchemaModels(b *strings.Builder, def *schema.SchemaDefinition) error {
	typeName := stringutil.ToPascalCase(def.Name)

	// Plain struct — fields only, no audit.
	fmt.Fprintf(b, "// %s represents the user-defined fields of a %s record.\n", typeName, def.Name)
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	for _, f := range def.Fields {
		writeField(b, f, false)
	}
	b.WriteString("}\n\n")

	// Create variant — same fields, required have no omitempty.
	fmt.Fprintf(b, "// %sCreate carries the user-supplied fields for creating a new %s.\n", typeName, def.Name)
	fmt.Fprintf(b, "type %sCreate struct {\n", typeName)
	for _, f := range def.Fields {
		writeField(b, f, false)
	}
	b.WriteString("}\n\n")

	// Update variant — all fields are pointers (PATCH semantics).
	fmt.Fprintf(b, "// %sUpdate carries the fields the caller wishes to change (PATCH semantics).\n", typeName)
	fmt.Fprintf(b, "type %sUpdate struct {\n", typeName)
	for _, f := range def.Fields {
		writeField(b, f, true)
	}
	b.WriteString("}\n\n")

	return nil
}

// writeField appends a single struct field line to b.
// When forUpdate is true, scalar types are wrapped in a pointer.
func writeField(b *strings.Builder, f schema.FieldDefinition, forUpdate bool) {
	goName := stringutil.ToPascalCase(f.Name)
	goType := resolvedType(f)

	if forUpdate {
		goType = ptrType(goType)
	}

	tag := jsonFieldTag(f.Name, f.Required, forUpdate)
	fmt.Fprintf(b, "\t%s %s %s\n", goName, goType, tag)
}

// resolvedType returns the Go type for a field, falling back to "any" when no
// information is available.
func resolvedType(f schema.FieldDefinition) string {
	if f.GoType != "" {
		return f.GoType
	}
	switch f.JSONType {
	case "string":
		if f.Format == "date-time" {
			return "time.Time"
		}
		return "string"
	case "number":
		return "float64"
	case "integer":
		return "int64"
	case "boolean":
		return "bool"
	case "array":
		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

// ptrType wraps base in a pointer unless it is already a pointer, slice, map,
// or interface type.
func ptrType(base string) string {
	if strings.HasPrefix(base, "*") ||
		strings.HasPrefix(base, "[]") ||
		strings.HasPrefix(base, "map[") ||
		base == "any" {
		return base
	}
	return "*" + base
}

// jsonFieldTag builds a struct tag string.
func jsonFieldTag(name string, required, forUpdate bool) string {
	if required && !forUpdate {
		return fmt.Sprintf("`json:%q`", name)
	}
	return fmt.Sprintf("`json:\"%s,omitempty\"`", name)
}

// ---------------------------------------------------------------------------
// client.go generation
// ---------------------------------------------------------------------------

// generateClient returns the content of client.go containing the Client struct
// and one set of CRUD methods per schema.
func (g *ClientGenerator) generateClient(defs []*schema.SchemaDefinition) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by stellar-drive; DO NOT EDIT.\n")
	b.WriteString("package sdkclient\n\n")

	b.WriteString(`import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
)

`)

	baseURL := g.baseURL
	if baseURL == "" {
		baseURL = "http://localhost:8080"
	}

	// Client struct.
	fmt.Fprintf(&b, `// Client is a typed HTTP client for the stellar-drive API.
// All methods are safe for concurrent use.
type Client struct {
	baseURL    string
	httpClient *http.Client
}

// NewClient creates a Client with the given base URL. When httpClient is nil,
// http.DefaultClient is used.
func NewClient(baseURL string, httpClient *http.Client) *Client {
	if baseURL == "" {
		baseURL = %q
	}
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &Client{baseURL: baseURL, httpClient: httpClient}
}

`, baseURL)

	// Shared private helpers.
	b.WriteString(clientHelpers())

	// Per-schema methods.
	for _, def := range defs {
		writeClientMethods(&b, def)
	}

	return b.String(), nil
}

// clientHelpers returns the private helper methods that are shared across all
// schema-specific CRUD methods.
func clientHelpers() string {
	return `// do executes req, checks for a non-2xx status, and decodes the JSON body
// into out. out may be nil if the caller does not expect a body.
func (c *Client) do(ctx context.Context, req *http.Request, out any) error {
	req = req.WithContext(ctx)
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("http: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read body: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		var apiErr APIError
		if jsonErr := json.Unmarshal(body, &apiErr); jsonErr != nil {
			return &APIError{StatusCode: resp.StatusCode, Message: string(body)}
		}
		apiErr.StatusCode = resp.StatusCode
		return &apiErr
	}

	if out != nil && len(body) > 0 {
		if err := json.Unmarshal(body, out); err != nil {
			return fmt.Errorf("decode response: %w", err)
		}
	}
	return nil
}

// newJSONRequest builds an HTTP request with a JSON-encoded body.
func (c *Client) newJSONRequest(method, path string, body any) (*http.Request, error) {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(body); err != nil {
		return nil, fmt.Errorf("encode body: %w", err)
	}
	req, err := http.NewRequest(method, c.baseURL+path, &buf)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	return req, nil
}

// newRequest builds a plain HTTP request with no body.
func (c *Client) newRequest(method, path string) (*http.Request, error) {
	req, err := http.NewRequest(method, c.baseURL+path, nil)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	return req, nil
}

`
}

// writeClientMethods appends the five CRUD methods for def to b.
func writeClientMethods(b *strings.Builder, def *schema.SchemaDefinition) {
	typeName := stringutil.ToPascalCase(def.Name)
	// Pluralise from the original schema name, not the PascalCase type name,
	// so "pet" → "pets" and the method is ListPets, not ListPetss.
	pluralTypeName := stringutil.ToPascalCase(stringutil.Pluralize(def.Name))
	// URL path uses the plural lower-case name, consistent with the REST adapter.
	basePath := "/" + strings.ToLower(stringutil.Pluralize(def.Name))

	// Create
	fmt.Fprintf(b, "// Create%s sends a POST request to create a new %s record.\n", typeName, def.Name)
	fmt.Fprintf(b, "func (c *Client) Create%s(ctx context.Context, input %sCreate) (*Document[%s], error) {\n", typeName, typeName, typeName)
	fmt.Fprintf(b, "\treq, err := c.newJSONRequest(http.MethodPost, %q, input)\n", basePath)
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"create %s: %%w\", err)\n\t}\n", def.Name)
	fmt.Fprintf(b, "\tvar env ResponseEnvelope[Document[%s]]\n", typeName)
	fmt.Fprintf(b, "\tif err := c.do(ctx, req, &env); err != nil {\n\t\treturn nil, fmt.Errorf(\"create %s: %%w\", err)\n\t}\n", def.Name)
	b.WriteString("\treturn &env.Data, nil\n}\n\n")

	// Get
	fmt.Fprintf(b, "// Get%s retrieves a single %s record by its entity ID.\n", typeName, def.Name)
	fmt.Fprintf(b, "func (c *Client) Get%s(ctx context.Context, id string) (*Document[%s], error) {\n", typeName, typeName)
	fmt.Fprintf(b, "\treq, err := c.newRequest(http.MethodGet, %q+\"/\"+id)\n", basePath)
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"get %s: %%w\", err)\n\t}\n", def.Name)
	fmt.Fprintf(b, "\tvar env ResponseEnvelope[Document[%s]]\n", typeName)
	fmt.Fprintf(b, "\tif err := c.do(ctx, req, &env); err != nil {\n\t\treturn nil, fmt.Errorf(\"get %s: %%w\", err)\n\t}\n", def.Name)
	b.WriteString("\treturn &env.Data, nil\n}\n\n")

	// List — method name uses the proper plural of the type name.
	fmt.Fprintf(b, "// List%s retrieves a paginated list of %s records.\n", pluralTypeName, def.Name)
	fmt.Fprintf(b, "func (c *Client) List%s(ctx context.Context, opts ListOptions) (*ListResult[Document[%s]], error) {\n", pluralTypeName, typeName)
	b.WriteString("\tq := url.Values{}\n")
	b.WriteString("\tif opts.Limit > 0 {\n\t\tq.Set(\"limit\", strconv.Itoa(opts.Limit))\n\t}\n")
	b.WriteString("\tif opts.Offset > 0 {\n\t\tq.Set(\"offset\", strconv.Itoa(opts.Offset))\n\t}\n")
	b.WriteString("\tif opts.Cursor != \"\" {\n\t\tq.Set(\"cursor\", opts.Cursor)\n\t}\n")
	fmt.Fprintf(b, "\tpath := %q\n", basePath)
	b.WriteString("\tif len(q) > 0 {\n\t\tpath += \"?\" + q.Encode()\n\t}\n")
	fmt.Fprintf(b, "\treq, err := c.newRequest(http.MethodGet, path)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"list %s: %%w\", err)\n\t}\n", def.Name)
	fmt.Fprintf(b, "\tvar env ResponseEnvelope[ListResult[Document[%s]]]\n", typeName)
	fmt.Fprintf(b, "\tif err := c.do(ctx, req, &env); err != nil {\n\t\treturn nil, fmt.Errorf(\"list %s: %%w\", err)\n\t}\n", def.Name)
	b.WriteString("\treturn &env.Data, nil\n}\n\n")

	// Update
	fmt.Fprintf(b, "// Update%s sends a PATCH request to partially update an existing %s record.\n", typeName, def.Name)
	fmt.Fprintf(b, "func (c *Client) Update%s(ctx context.Context, id string, input %sUpdate) (*Document[%s], error) {\n", typeName, typeName, typeName)
	fmt.Fprintf(b, "\treq, err := c.newJSONRequest(http.MethodPatch, %q+\"/\"+id, input)\n", basePath)
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"update %s: %%w\", err)\n\t}\n", def.Name)
	fmt.Fprintf(b, "\tvar env ResponseEnvelope[Document[%s]]\n", typeName)
	fmt.Fprintf(b, "\tif err := c.do(ctx, req, &env); err != nil {\n\t\treturn nil, fmt.Errorf(\"update %s: %%w\", err)\n\t}\n", def.Name)
	b.WriteString("\treturn &env.Data, nil\n}\n\n")

	// Delete
	fmt.Fprintf(b, "// Delete%s sends a DELETE request to remove a %s record by its entity ID.\n", typeName, def.Name)
	fmt.Fprintf(b, "func (c *Client) Delete%s(ctx context.Context, id string) error {\n", typeName)
	fmt.Fprintf(b, "\treq, err := c.newRequest(http.MethodDelete, %q+\"/\"+id)\n", basePath)
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn fmt.Errorf(\"delete %s: %%w\", err)\n\t}\n", def.Name)
	fmt.Fprintf(b, "\tif err := c.do(ctx, req, nil); err != nil {\n\t\treturn fmt.Errorf(\"delete %s: %%w\", err)\n\t}\n", def.Name)
	b.WriteString("\treturn nil\n}\n\n")
}

// ---------------------------------------------------------------------------
// errors.go generation
// ---------------------------------------------------------------------------

// generateErrors returns the content of errors.go containing the APIError type.
func (g *ClientGenerator) generateErrors() string {
	return `// Code generated by stellar-drive; DO NOT EDIT.
package sdkclient

import (
	"encoding/json"
	"fmt"
)

// ErrorDetail provides additional context for a specific validation or
// application-level error.
type ErrorDetail struct {
	Field   string ` + "`json:\"field,omitempty\"`" + `
	Message string ` + "`json:\"message\"`" + `
	Code    string ` + "`json:\"code,omitempty\"`" + `
}

// ErrorResponse is the JSON body returned by the server on non-2xx responses.
type ErrorResponse struct {
	Code    string        ` + "`json:\"code,omitempty\"`" + `
	Message string        ` + "`json:\"message\"`" + `
	Details []ErrorDetail ` + "`json:\"details,omitempty\"`" + `
}

// APIError is returned by Client methods when the server responds with a
// non-2xx HTTP status code. It implements the error interface.
type APIError struct {
	StatusCode int
	Code       string
	Message    string
	Details    []ErrorDetail
}

// Error implements the error interface.
func (e *APIError) Error() string {
	if e.Code != "" {
		return fmt.Sprintf("api error %d (%s): %s", e.StatusCode, e.Code, e.Message)
	}
	return fmt.Sprintf("api error %d: %s", e.StatusCode, e.Message)
}

// UnmarshalJSON populates APIError from the ErrorResponse JSON shape.
func (e *APIError) UnmarshalJSON(data []byte) error {
	// Use a local alias to avoid infinite recursion.
	type alias ErrorResponse
	var r alias
	if err := json.Unmarshal(data, &r); err != nil {
		return err
	}
	e.Code = r.Code
	e.Message = r.Message
	e.Details = r.Details
	return nil
}
`
}
